### PR TITLE
Data prep

### PR DESCRIPTION
**Pull request by Stefan415849**

### CODE REVIEW

**Comment by Ranim1996** [comment]
the pull request must be from your branch to the development

**Review by rawan-a-d — CHANGES_REQUESTED** [review]
See comments

**Review by Ranim1996 — CHANGES_REQUESTED** [review]
.

**Comment by dennycox** [comment]
<p>Agreed</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/14/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dennycox** [comment]
<p>Me neither</p><p> </p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/14/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by dennycox** [comment]
<p>Graph not showing</p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/14/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by dennycox — APPROVED** [review]
Some small things need to change but can also be done after merging, see my comments

**Comment by jarnovdh15** [comment]
<p>and make it a sample in stead of everything</p><p> </p>

---

 <a href='https://app.reviewnb.com/rawan-a-d/Air-Quality-Prediction/pull/14/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by rawan-a-d — APPROVED** [review]

**Review by Ranim1996 — APPROVED** [review]

**Pull request merged**
